export const LANGUAGES = [
  { code: 'uz', name: "O'zbek", nativeName: "O'zbek tili" },
  { code: 'ru', name: 'Русский', nativeName: 'Русский язык' },
  { code: 'en', name: 'English', nativeName: 'English' },
];

const translations = {
  uz: {
    home: 'Bosh sahifa', stats: 'Statistika', budget: 'Byudjet', settings: 'Sozlamalar', ai: 'AI',
    welcomeGuest: 'Salom!', guestUser: "do'stim", aiGreetingWithName: "Salom, {name}! Men sizning AI yordamchingizman. Har qanday savolingizga javob bera olaman — moliya, texnologiya, ta'lim yoki boshqa mavzular. Shuningdek, balansingiz, xarajatlaringiz va byudjetingizni tahlil qilishga ham yordam beraman. Nima haqida so'ramoqchisiz?",
    welcome: 'Salom, {name}!', dashboardSubtitle: 'Moliyaviy hisobotingiz va boshqaruv paneli', currentBalance: 'Joriy balans',
    income: 'Daromad', incomes: 'Daromadlar', expense: 'Xarajat', expenses: 'Xarajatlar', balance: 'Balans',
    addIncome: "Daromad qo'shish", addExpense: "Xarajat qo'shish", recentTransactions: "So'nggi amallar", viewAll: 'Barchasi',
    noTransactions: 'Amallar topilmadi', noTransactionsDescription: 'Daromad yoki xarajatlaringizni kiritishni boshlang',
    incomeAdded: "Daromad muvaffaqiyatli qo'shildi!", expenseAdded: "Xarajat muvaffaqiyatli qo'shildi!", transactionDeleted: "Tranzaksiya o'chirildi",
    transactionsTitle: 'Amallar tarixi', transactionsSubtitle: "Barcha daromad va xarajatlaringiz ro'yxati", all: 'Barchasi', today: 'Bugun', yesterday: 'Kecha',
    filteredBalance: 'Filtrlangan balans', totalExpense: 'Jami xarajat', totalIncome: 'Jami daromad', noData: "Ma'lumotlar mavjud emas", noDataDescription: "Tanlangan filtr bo'yicha hech qanday amal topilmadi",
    statsTitle: 'Moliya tahlili', statsSubtitle: 'Daromad va xarajatlaringiz dinamik tahlili', week: 'Hafta', month: 'Oy', year: 'Yil',
    expenseDistribution: 'Xarajatlar taqsimoti', incomeDistribution: 'Daromadlar taqsimoti', noPeriodData: "Ushbu davrda {type} mavjud emas", topCategories: 'Top {type}', notEnoughData: "Tahlil qilish uchun yetarli ma'lumot yo'q", noPeriodEntry: "Ushbu davr uchun {type} kiritilmagan",
    budgetTitle: 'Oylik byudjetlar', budgetSubtitle: "Kategoriyalar bo'yicha oylik xarajatlar limitini o'rnating", noLimit: "Limit yo'q", spent: 'sarflandi', setLimit: "Limit o'rnatish uchun bosing", setLimitTitle: '{category} limitini belgilash', monthlyLimit: 'Oylik limit summasi ({currency})', limitPlaceholder: "0 (o'chirish uchun bo'sh qoldiring)", save: 'Saqlash', budgetSet: '{category} uchun byudjet belgilandi!', budgetRemoved: "{category} byudjeti o'chirildi!",
    transactionType: 'Amal turi', amount: 'Summa ({currency})', category: 'Kategoriya', date: 'Sana', note: 'Izoh', notePlaceholder: "Nima uchunligini yozing...", validAmount: "Iltimos, to'g'ri summa kiriting", selectCategory: 'Iltimos, kategoriya tanlang',
    deleteTransactionConfirm: "Ushbu tranzaksiyani o'chirib tashlamoqchimisiz?", other: 'Boshqa', noNote: 'Izohsiz',
    language: 'Til', languageDescription: 'Ilova interfeysi tili', settingsSubtitle: "Ilovani o'zingizga moslashtiring", selectLanguage: 'Tilni tanlash', languageChanged: "Ilova tili o'zgartirildi",
    primaryCurrency: 'Asosiy valyuta', currencyDescription: "Kiritiladigan mablag'lar uchun valyuta shakli", selectCurrency: 'Valyuta tanlash', currencyChanged: 'Asosiy valyuta: {currency} ({symbol}) ga o‘zgartirildi.', currencyConverted: 'Barcha summalar {currency} ({symbol}) ga rasmiy kurs bo‘yicha o‘tkazildi.', currencyFailed: "Valyutani o'zgartirib bo'lmadi.",
    theme: 'Mavzu', themeDescription: "Qorong'u, yorug' yoki tizim mavzusi", selectTheme: 'Mavzuni tanlash', system: 'Tizim', dark: "Qorong'u", light: "Yorug'", themeChanged: 'Mavzu: {theme} rejimiga o‘zgartirildi',
    exportData: "Ma'lumotlarni eksport qilish", exportDescription: 'Zaxira fayl (JSON) yuklab olish', importData: 'Zaxiradan tiklash (Import)', importDescription: "JSON fayldan ma'lumotlarni yuklash", about: 'Ilova haqida', aboutDescription: "Tizim ma'lumotlari va ishlab chiquvchi", clearData: "Ma'lumotlarni tozalash", clearDescription: "Barcha tranzaksiyalarni o'chirish", exported: "Ma'lumotlar muvaffaqiyatli eksport qilindi!", exportFailed: 'Eksportda xatolik yuz berdi', clearConfirm: "Barcha ma'lumotlarni o'chirib tashlamoqchimisiz? Ushbu amalni qaytarib bo'lmaydi!", cleared: "Barcha ma'lumotlar tozalandi", appAbout: "Ushbu Telegram Mini App sizning shaxsiy moliyaviy daromad va xarajatlaringizni kuzatish hamda byudjet nazoratini olib borish uchun maxsus ishlab chiqilgan.", developer: 'Ishlab chiquvchi: Antigravity AI Team',
    aiTitle: 'AI Maslahatchi', aiSubtitle: "Sun'iy intellekt yordamchisi — har qanday savolga javob", aiGreeting: "Salom! Men sizning AI yordamchingizman. Har qanday savolingizga javob bera olaman — moliya, texnologiya, ta'lim yoki boshqa mavzular. Shuningdek, balansingiz, xarajatlaringiz va byudjetingizni tahlil qilishga ham yordam beraman. Nima haqida so'ramoqchisiz?", aiThinking: 'AI maslahatchi tahlil qilmoqda...', quickQuestions: 'Tezkor savollar:', questionPlaceholder: 'Savolingizni yozing...', aiError: 'Xatolik yuz berdi. Iltimos, qayta urinib ko‘ring.', aiTimeout: 'Javob uzoq davom etdi. Savolni qisqaroq qilib qayta yuboring.', aiOffline: "Internet aloqasi yo'q yoki server javob bermadi. Qayta urinib ko'ring.", promptExpenses: '📊 Xarajatlarimni tahlil qil', promptSavings: "💡 Pul tejash bo'yicha maslahat", promptBudget: '📈 Byudjetim ahvoli qanday?',
    voiceAdd: "Ovoz orqali tranzaksiya qo'shish", voiceStop: "Yozishni to'xtatish", voiceProcessing: 'Ovoz tahlil qilinmoqda', voiceAdded: '{type} qo‘shildi: {amount} {currency}', voiceFailed: "Ovozli xabarni tahlil qilib bo'lmadi.", voiceTimeout: "Ovoz tahlili uzoq davom etdi. Qayta urinib ko'ring.", voiceRetry: "Ovozli xabarni qayta yuboring.", voiceUnsupported: "Bu qurilmada mikrofon yozuvi qo'llab-quvvatlanmaydi.", voiceNotRecorded: "Ovoz yozilmadi. Qayta urinib ko'ring.", voiceNotHeard: "Ovoz eshitilmadi. Gapirib, qayta urinib ko'ring.", microphonePermission: 'Mikrofondan foydalanishga ruxsat bering.',
  },
  ru: {
    home: 'Главная', stats: 'Статистика', budget: 'Бюджет', settings: 'Настройки', ai: 'AI',
    welcomeGuest: 'Здравствуйте!', guestUser: 'друг', aiGreetingWithName: 'Здравствуйте, {name}! Я ваш AI-помощник. Могу ответить на вопросы о финансах, технологиях, образовании и других темах, а также помочь проанализировать баланс, расходы и бюджет. О чём хотите спросить?',
    welcome: 'Здравствуйте, {name}!', dashboardSubtitle: 'Ваш финансовый отчёт и панель управления', currentBalance: 'Текущий баланс',
    income: 'Доход', incomes: 'Доходы', expense: 'Расход', expenses: 'Расходы', balance: 'Баланс',
    addIncome: 'Добавить доход', addExpense: 'Добавить расход', recentTransactions: 'Последние операции', viewAll: 'Все',
    noTransactions: 'Операций нет', noTransactionsDescription: 'Начните добавлять доходы или расходы', incomeAdded: 'Доход успешно добавлен!', expenseAdded: 'Расход успешно добавлен!', transactionDeleted: 'Транзакция удалена',
    transactionsTitle: 'История операций', transactionsSubtitle: 'Список всех доходов и расходов', all: 'Все', today: 'Сегодня', yesterday: 'Вчера', filteredBalance: 'Баланс по фильтру', totalExpense: 'Всего расходов', totalIncome: 'Всего доходов', noData: 'Данные отсутствуют', noDataDescription: 'По выбранному фильтру операций не найдено',
    statsTitle: 'Финансовый анализ', statsSubtitle: 'Динамический анализ доходов и расходов', week: 'Неделя', month: 'Месяц', year: 'Год', expenseDistribution: 'Распределение расходов', incomeDistribution: 'Распределение доходов', noPeriodData: 'За этот период {type} отсутствуют', topCategories: 'Топ {type}', notEnoughData: 'Недостаточно данных для анализа', noPeriodEntry: 'За этот период {type} не добавлены',
    budgetTitle: 'Месячные бюджеты', budgetSubtitle: 'Установите месячные лимиты расходов по категориям', noLimit: 'Нет лимита', spent: 'потрачено', setLimit: 'Нажмите, чтобы установить лимит', setLimitTitle: 'Установить лимит: {category}', monthlyLimit: 'Сумма месячного лимита ({currency})', limitPlaceholder: '0 (оставьте пустым, чтобы удалить)', save: 'Сохранить', budgetSet: 'Бюджет для {category} установлен!', budgetRemoved: 'Бюджет для {category} удалён!',
    transactionType: 'Тип операции', amount: 'Сумма ({currency})', category: 'Категория', date: 'Дата', note: 'Примечание', notePlaceholder: 'Напишите назначение...', validAmount: 'Введите корректную сумму', selectCategory: 'Выберите категорию', deleteTransactionConfirm: 'Удалить эту транзакцию?', other: 'Другое', noNote: 'Без примечания',
    language: 'Язык', languageDescription: 'Язык интерфейса приложения', settingsSubtitle: 'Настройте приложение под себя', selectLanguage: 'Выберите язык', languageChanged: 'Язык приложения изменён', primaryCurrency: 'Основная валюта', currencyDescription: 'Валюта для вводимых сумм', selectCurrency: 'Выберите валюту', currencyChanged: 'Основная валюта изменена на {currency} ({symbol}).', currencyConverted: 'Все суммы конвертированы в {currency} ({symbol}) по официальному курсу.', currencyFailed: 'Не удалось изменить валюту.',
    theme: 'Тема', themeDescription: 'Тёмная, светлая или системная тема', selectTheme: 'Выберите тему', system: 'Системная', dark: 'Тёмная', light: 'Светлая', themeChanged: 'Тема изменена: {theme}', exportData: 'Экспорт данных', exportDescription: 'Скачать резервный файл (JSON)', importData: 'Восстановить из копии', importDescription: 'Загрузить данные из JSON-файла', about: 'О приложении', aboutDescription: 'Сведения о системе и разработчике', clearData: 'Очистить данные', clearDescription: 'Удалить все транзакции', exported: 'Данные успешно экспортированы!', exportFailed: 'Ошибка экспорта', clearConfirm: 'Удалить все данные? Это действие нельзя отменить!', cleared: 'Все данные очищены', appAbout: 'Это Telegram Mini App для учёта личных доходов и расходов, а также контроля бюджета.', developer: 'Разработчик: Antigravity AI Team',
    aiTitle: 'AI-консультант', aiSubtitle: 'Помощник на базе ИИ — ответы на любые вопросы', aiGreeting: 'Здравствуйте! Я ваш AI-помощник. Могу ответить на вопросы о финансах, технологиях, образовании и других темах, а также помочь проанализировать баланс, расходы и бюджет. О чём хотите спросить?', aiThinking: 'AI-консультант анализирует...', quickQuestions: 'Быстрые вопросы:', questionPlaceholder: 'Напишите вопрос...', aiError: 'Произошла ошибка. Попробуйте ещё раз.', aiTimeout: 'Ответ занял слишком много времени. Отправьте более короткий вопрос.', aiOffline: 'Нет подключения к интернету или сервер не отвечает. Попробуйте ещё раз.', promptExpenses: '📊 Проанализируй мои расходы', promptSavings: '💡 Советы по экономии денег', promptBudget: '📈 Как мой бюджет?', voiceAdd: 'Добавить транзакцию голосом', voiceStop: 'Остановить запись', voiceProcessing: 'Анализ голосовой записи', voiceAdded: '{type} добавлен: {amount} {currency}', voiceFailed: 'Не удалось обработать голосовое сообщение.', voiceTimeout: 'Анализ голоса занял слишком много времени. Попробуйте ещё раз.', voiceRetry: 'Отправьте голосовое сообщение ещё раз.', voiceUnsupported: 'Запись с микрофона не поддерживается на этом устройстве.', voiceNotRecorded: 'Голос не записан. Попробуйте ещё раз.', voiceNotHeard: 'Голос не слышен. Пожалуйста, говорите и попробуйте ещё раз.', microphonePermission: 'Разрешите доступ к микрофону.',
  },
  en: {
    home: 'Home', stats: 'Statistics', budget: 'Budget', settings: 'Settings', ai: 'AI',
    welcomeGuest: 'Hello!', guestUser: 'there', aiGreetingWithName: 'Hello, {name}! I am your AI assistant. I can answer questions about finance, technology, education, and more, and help analyse your balance, expenses, and budget. What would you like to ask?',
    welcome: 'Hello, {name}!', dashboardSubtitle: 'Your financial report and dashboard', currentBalance: 'Current balance', income: 'Income', incomes: 'Income', expense: 'Expense', expenses: 'Expenses', balance: 'Balance', addIncome: 'Add income', addExpense: 'Add expense', recentTransactions: 'Recent transactions', viewAll: 'View all', noTransactions: 'No transactions found', noTransactionsDescription: 'Start by adding your income or expenses', incomeAdded: 'Income added successfully!', expenseAdded: 'Expense added successfully!', transactionDeleted: 'Transaction deleted',
    transactionsTitle: 'Transaction history', transactionsSubtitle: 'A list of all your income and expenses', all: 'All', today: 'Today', yesterday: 'Yesterday', filteredBalance: 'Filtered balance', totalExpense: 'Total expenses', totalIncome: 'Total income', noData: 'No data available', noDataDescription: 'No transactions match the selected filter',
    statsTitle: 'Financial analysis', statsSubtitle: 'Dynamic analysis of your income and expenses', week: 'Week', month: 'Month', year: 'Year', expenseDistribution: 'Expense distribution', incomeDistribution: 'Income distribution', noPeriodData: 'No {type} during this period', topCategories: 'Top {type}', notEnoughData: 'Not enough data to analyse', noPeriodEntry: 'No {type} were added for this period',
    budgetTitle: 'Monthly budgets', budgetSubtitle: 'Set monthly spending limits by category', noLimit: 'No limit', spent: 'spent', setLimit: 'Tap to set a limit', setLimitTitle: 'Set limit for {category}', monthlyLimit: 'Monthly limit amount ({currency})', limitPlaceholder: '0 (leave blank to remove)', save: 'Save', budgetSet: 'Budget set for {category}!', budgetRemoved: 'Budget removed for {category}!',
    transactionType: 'Transaction type', amount: 'Amount ({currency})', category: 'Category', date: 'Date', note: 'Note', notePlaceholder: 'Describe the purpose...', validAmount: 'Please enter a valid amount', selectCategory: 'Please select a category', deleteTransactionConfirm: 'Do you want to delete this transaction?', other: 'Other', noNote: 'No note',
    language: 'Language', languageDescription: 'App interface language', settingsSubtitle: 'Personalise the app for yourself', selectLanguage: 'Select language', languageChanged: 'App language changed', primaryCurrency: 'Primary currency', currencyDescription: 'Currency for entered amounts', selectCurrency: 'Select currency', currencyChanged: 'Primary currency changed to {currency} ({symbol}).', currencyConverted: 'All amounts converted to {currency} ({symbol}) at the official rate.', currencyFailed: 'Could not change the currency.',
    theme: 'Theme', themeDescription: 'Dark, light, or system theme', selectTheme: 'Select theme', system: 'System', dark: 'Dark', light: 'Light', themeChanged: 'Theme changed to {theme}', exportData: 'Export data', exportDescription: 'Download a backup file (JSON)', importData: 'Restore from backup', importDescription: 'Upload data from a JSON file', about: 'About app', aboutDescription: 'System and developer information', clearData: 'Clear data', clearDescription: 'Delete all transactions', exported: 'Data exported successfully!', exportFailed: 'Export failed', clearConfirm: 'Delete all data? This action cannot be undone!', cleared: 'All data has been cleared', appAbout: 'This Telegram Mini App helps you track personal income and expenses and manage your budget.', developer: 'Developer: Antigravity AI Team',
    aiTitle: 'AI advisor', aiSubtitle: 'AI assistant — answers to any question', aiGreeting: 'Hello! I am your AI assistant. I can answer questions about finance, technology, education, and more, and help analyse your balance, expenses, and budget. What would you like to ask?', aiThinking: 'AI advisor is analysing...', quickQuestions: 'Quick questions:', questionPlaceholder: 'Write your question...', aiError: 'Something went wrong. Please try again.', aiTimeout: 'The response took too long. Please send a shorter question.', aiOffline: 'No internet connection or the server is not responding. Please try again.', promptExpenses: '📊 Analyse my expenses', promptSavings: '💡 Tips for saving money', promptBudget: '📈 How is my budget doing?', voiceAdd: 'Add a transaction by voice', voiceStop: 'Stop recording', voiceProcessing: 'Analysing voice recording', voiceAdded: '{type} added: {amount} {currency}', voiceFailed: 'Could not process the voice message.', voiceTimeout: 'Voice analysis took too long. Please try again.', voiceRetry: 'Please send the voice message again.', voiceUnsupported: 'Microphone recording is not supported on this device.', voiceNotRecorded: 'No voice was recorded. Please try again.', voiceNotHeard: 'No speech was detected. Please speak and try again.', microphonePermission: 'Allow microphone access.',
  },
};

const categoryTranslations = {
  food: ['Ovqat', 'Еда', 'Food'], transport: ['Transport', 'Транспорт', 'Transport'], home: ['Uy-joy', 'Жильё', 'Home'], health: ["Sog'liq", 'Здоровье', 'Health'], entertainment: ["Ko'ngilochar", 'Развлечения', 'Entertainment'], clothing: ['Kiyim', 'Одежда', 'Clothing'], education: ["Ta'lim", 'Образование', 'Education'], utilities: ['Kommunal', 'Коммунальные услуги', 'Utilities'], phone: ['Aloqa', 'Связь', 'Phone'], gift: ["Sovg'a", 'Подарок', 'Gift'], grocery: ["Oziq-ovqat", 'Продукты', 'Groceries'], other_expense: ['Boshqa', 'Другое', 'Other'], salary: ['Ish haqi', 'Зарплата', 'Salary'], freelance: ['Freelance', 'Фриланс', 'Freelance'], investment: ['Investitsiya', 'Инвестиции', 'Investment'], gift_income: ["Sovg'a", 'Подарок', 'Gift'], business: ['Biznes', 'Бизнес', 'Business'], other_income: ['Boshqa', 'Другое', 'Other'],
};

export function t(language, key, values = {}) {
  const template = translations[language]?.[key] || translations.uz[key] || key;
  return template.replace(/\{(\w+)\}/g, (_, name) => values[name] ?? `{${name}}`);
}

export function getLocale(language) {
  return { uz: 'uz-UZ', ru: 'ru-RU', en: 'en-US' }[language] || 'uz-UZ';
}

export function getCategoryName(category, language) {
  const index = { uz: 0, ru: 1, en: 2 }[language] ?? 0;
  return categoryTranslations[category?.id]?.[index] || category?.name || t(language, 'other');
}
